[package]
name = "swapping"
version = "0.0.0"

[addresses]
swap_account = "9da47f04d7a78afdad00fdc6052c9f53900440af998b6599f24e8e71091fb7bb"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "mainnet" }

[dependencies.AnimeSwapV1]
local = './v1-core/Swap'

[dependencies.Liquidswap]
local = './liquidswap/'

[dependencies.LiquidswapRouterV2]
local = './liquidswap/liquidswap_router_v2/'

[dependencies.Cetue-AMM]
local = './cetus-amm/aptos/'

[dependencies.PancakeSwap]
local = './pancake-contracts-move/pancake-swap/'