[package]
name = "SwapGPT"
version = "0.0.1"

[addresses]
swap_account = "6d579f1e8dd27b95069ebb53a9bb1f66b9c6c3a369f815d307fc506de05170d3"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "mainnet" }

[dependencies.AnimeSwapV1]
local = './v1-core/Swap'

[dependencies.Liquidswap]
local = './liquidswap/'

[dependencies.LiquidswapRouterV2]
local = './liquidswap/liquidswap_router_v2/'

[dependencies.Cetue-AMM]
local = './cetus-amm/aptos/'

[dependencies.PancakeSwap]
local = './pancake-contracts-move/pancake-swap/'

[dependencies.aux]
local = './aux-exchange/aptos/contract/auxexch/'
